server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5726/graduation-design?useUnicode=true&characterEncoding=utf8
    username: root
    password: ju147...
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 20
      min-idle: 10
      max-idle: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 映射配置文件位置
  type-aliases-package: com.jus.domain  #定义包别名
  configuration:
    call-setters-on-nulls: true   # 防止返回的字段不全
